import Head from 'next/head';
import { Button } from 'antd';
import { Checkbox, Row, Col } from 'antd';
import { useSession, signIn, signOut } from "next-auth/react";
import { useState } from 'react';
import Image from 'next/image';


const layout = {
  labelCol: {
    span: 8,
  },
  wrapperCol: {
    span: 16,
  },
};

/* eslint-disable no-template-curly-in-string */
const validateMessages = {
  required: '${label} is required!',
  types: {
    email: '${label} is not a valid email!',
    number: '${label} is not a valid number!',
  },
  number: {
    range: '${label} must be between ${min} and ${max}',
  },
};

/* eslint-enable no-template-curly-in-string */


export default function Home() {
  const { data: session } = useSession()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <section id='register'>
        <div className='container'>
          <div className='register-main'>
            <Col lg={{ span: 11, offset: 7 }} md={{ span: 15, offset: 5 }}>
              <Button block={true} style={{ height: "45px", display: "block", margin: "30px auto", fontSize: "17px" }}
                onClick={() => signIn("google", process.env.GOOGLE_REDIRECT_URI)}>
                Sign in With Google
                <Image alt="Picture of the author"
                  width={20}
                  height={20}
                  style={{ borderRadius: "50%", marginLeft: "15px" }}
                  src='/images/google.png' />
              </Button>
            </Col>
            <Col lg={{ span: 11, offset: 7 }} md={{ span: 15, offset: 5 }}>
              <Button
                block={true}
                style={{ height: "45px", display: "block", margin: "30px auto", fontSize: "17px" }}
                onClick={() => signIn("Apple", process.env.GOOGLE_REDIRECT_URI)}>
                Sign in With Apple
                <Image alt="Picture of the author"
                  width={20}
                  height={20}
                  style={{ borderRadius: "50%", marginLeft: "15px" }}
                  src='/images/apple.png' />
              </Button>
            </Col>
            <Col lg={{ span: 11, offset: 7 }} md={{ span: 15, offset: 5 }}>
              <Button href='./directSignup'
                block={true}
                style={{ height: "45px", display: "block", margin: "30px auto", fontSize: "17px" }}>
                Sign in With Email
                <Image alt="Picture of the author"
                  width={20}
                  height={20}
                  style={{ marginLeft: "15px", marginTop: "5px" }}
                  src='/images/email.png' />
              </Button>
            </Col>
            <Col lg={{ span: 11, offset: 7 }} md={{ span: 15, offset: 5 }} sm={{ span: 7, offset: 2 }}>
              <hr />
              <Row style={{ marginTop: "25px" }}>
                <Col offset={4} span={4}>
                  <p style={{ fontSize: "18px" }}>
                    or
                  </p>
                </Col>
                <Col offset={5} span={11}>
                  <Button href='./login'
                    block={true}
                    size='large'
                    style={{ backgroundColor: 'rgb(125 211 252)', color: 'rgb(15 23 42)' }}>
                    Login
                  </Button>
                </Col>
              </Row>
            </Col>
          </div>
        </div>
      </section>
    </>
  )
}
