import Head from 'next/head';
import Link from "next/link";
import { Button, Upload } from 'antd';
import ImgCrop from 'antd-img-crop';
import Image from "next/image";
import { Row, Col } from 'antd';
import { useSession, signIn, signOut } from "next-auth/react";
import { useState, useEffect } from 'react';
import jwt from "jsonwebtoken";
import axios from "axios";


axios.defaults.headers.post["Content-Type"] = "application/json";

axios.interceptors.response.use(null, error => {
    const expectedErrors =
        error.response &&
        error.response.status >= 400 &&
        error.response.status < 500;
    if (!expectedErrors) {
        console.log(error)
    }
    return Promise.reject(error)
});


/* eslint-enable no-template-curly-in-string */

export default function Home() {
    const { data: session } = useSession()
    const [fileList, setFileList] = useState([]);
    const [decodedToken, setDecodedToken] = useState();

    const jwtsecret =process.env.JWT_SECRET;
    const url1 = process.env.URL1;

    useEffect(() => {
        const token = localStorage.getItem('token')
        const decoded = jwt.decode(token, jwtsecret);
        if (Date.now() / 1000 < parseInt(decoded?.exp)) {
            setDecodedToken(decoded)
        }
    }
        , [])


    const onChange = ({ fileList: newFileList }) => {
        if (fileList.length < 2) {
            setFileList(newFileList);
        }
    };


    const handleSend = async () => {
        let res = await axios.post(url1, fileList)
        console.log(res);
    }

    if (!decodedToken) {
        return (
            <div style={{ textAlign: "center", marginTop: "200px" }}>
                <p >your login is expired</p>
                <Button href='/login' block={true}
                    style={{ backgroundColor: 'rgb(125 211 252)', color: 'rgb(15 23 42)', width: "150px" }} >
                    go to login page
                </Button>
            </div>
        )
    }



    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <section style={{ border: "1px solid rgb(30 41 59)", borderRadius: "8px", marginTop: "20px" }}>
                <div className='container'>
                    <Row>
                        <Col style={{ marginTop: "30px", marginLeft: "40px" }}>
                            {/* <Image alt="Picture of the author"
                                width={100}
                                height={100}
                                style={{ borderRadius: "50%" }}
                            // src='https://optimise2.assets-servd.host/maniacal-finch/production/animals/amur-tiger-01-01.jpg?w=1200&h=630&q=82&auto=format&fit=clip&dm=1658935145&s=42eaff37ee45905b3f1a70241c25d007'
                            /> */}
                        </Col>
                    </Row>
                    <Row>
                        <Col
                            lg={{ span: 11, offset: 1 }}
                            md={{ span: 13, offset: 2 }}
                            sm={{ span: 14, offset: 2 }}
                            xs={{ span: 14, offset: 2 }}
                            style={{ marginTop: "50px", marginBottom: "50px" }}>
                            <div style={{ display: "block" }}>
                                <h3>User Info</h3>
                                <p style={{ color: "#3bb944" }}>Username :
                                    <span
                                        style={{ color: "#c2ccce" }}>{session ? session.username : decodedToken.username}
                                    </span>
                                </p>
                                <p style={{ color: "#3bb944" }}>email :
                                    <span style={{ color: "#c2ccce" }}>
                                        {session ? session.email : decodedToken.email}
                                    </span>
                                </p>
                            </div>
                        </Col>
                        <Col
                            lg={{ span: 5 }}
                            md={{ span: 7 }}
                            sm={{ span: 8 }}
                            xs={{ span: 8 }}
                            style={{ marginTop: "50px", marginBottom: "50px" }}>
                            <ImgCrop rotationSlider>
                                <Upload
                                    maxCount={1}
                                    listType="picture-card"
                                    fileList={fileList}
                                    onChange={onChange}
                                    style={{ color: "red" }}
                                >
                                    {fileList.length < 1 && '+ Upload'}
                                </Upload>
                            </ImgCrop>
                        </Col>
                        <Col
                            lg={{ span: 3 }}
                            md={{ span: 5, offset: 3 }}
                            sm={{ span: 8, offset: 5 }}
                            xs={{ span: 8, offset: 5 }}
                            style={{ marginTop: "50px", marginBottom: "50px", color: "red" }}>
                            <Button block={true} onClick={e => handleSend()}
                                style={{ backgroundColor: 'rgb(125 211 252)', color: 'rgb(15 23 42)' }} >
                                Convert
                            </Button>
                            <Button href='/payment' block={true}
                                style={{ backgroundColor: 'rgb(125 211 252)', color: 'rgb(15 23 42)', marginTop: "25px" }} >
                                Buy Subscription
                            </Button>
                        </Col>
                    </Row>
                </div>
            </section>
        </>
    )
}
